# Site settings
title: Hackhers
email: rutgers.hackhers@gmail.com
description: "Hackhers is organized for women. At this hackathon, women and men will get involved in learning, planning and developing apps that will foster growth and productivity among women who want to code."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary:  66ccff #80B3FF
  secondary:  721794 #6e256e #609732 #FD6E8A #66ccff
  secondary-dark: 66ccff #A2122F
  
# Footer settings
footer:
  #copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/RutgersWCS/

# Postal address (add as many lines as necessary)
address:
  - line: Busch Campus Center
  - line: 604 Bartholomew Road
  - line: Piscataway, NJ 08854
  
# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
